version:
  jquery: 3.1.1
  jquery_migrate: 3.0.0
  bootstrap: 3.3.7
  font_awesome: 4.7.0
  require: 2.3.3

google_analytics_id: UA-77162159-1

repository: https://github.com/Y-Lab/Y-GRE-Frame

timezone: Asia/Shanghai

name: Y-English GRE Test Preparation Framework
alias: Y-GRE Frame
author: iROCKBUNNY
author_url: http://irockbunny.com
organization: Y-English
organization_url: http://www.y-english.org
description: The Y-English GRE Test Preparation Framework
url: hhttp://frame.y-gre.org
contact: dev@y-english.org

logo: /apple-touch-icon.png

gems:
- jekyll-seo-tag
- jekyll-sitemap

exclude:
- .gitignore
- .travis.yml
- LICENSE
- README.md
- CNAME
- Gemfile
- Gemfile.lock
- script
- vendor