google_analytics_id: UA-77162159-1

repository: https://github.com/Y-Lab/Y-GRE-Frame

timezone: Asia/Shanghai
lang: zh_CN

title: Y-English GRE Test Preparation Framework
alias: Y-GRE Frame
description: The Y-English GRE Test Preparation Framework
url: hhttp://frame.y-gre.org

author: iROCKBUNNY
author_url: http://irockbunny.com
organization: Y-English
organization_url: https://y-english.org

contact: dev@y-english.org

image: /apple-touch-icon.png
logo: /apple-touch-icon.png

plugins:
- jekyll-seo-tag
- jekyll-sitemap

exclude:
- .gitignore
- .travis.yml
- LICENSE
- README.md
- CNAME
- Gemfile
- Gemfile.lock
- script
- vendor